from __future__ import annotations


NEWS_SOURCES = [
    {
        "name": "BioBioChile",
        "source_type": "nacional",
        "base_url": "https://www.biobiochile.cl",
        "rss_urls": ["https://www.biobiochile.cl/feed/"],
        "sitemap_urls": [
            "https://www.biobiochile.cl/news-sitemap.xml",
            "https://www.biobiochile.cl/static/sitemap.xml",
            "https://www.biobiochile.cl/sitemap.xml",
        ],
    },
    {
        "name": "CNN Chile",
        "source_type": "nacional",
        "base_url": "https://www.cnnchile.com",
        "rss_urls": ["https://www.cnnchile.com/feed/"],
        "sitemap_urls": ["https://www.cnnchile.com/sitemap.xml"],
    },
    {
        "name": "El Mostrador",
        "source_type": "nacional",
        "base_url": "https://www.elmostrador.cl",
        "rss_urls": ["https://www.elmostrador.cl/feed/"],
        "sitemap_urls": ["https://www.elmostrador.cl/sitemap.xml"],
    },
    {
        "name": "La Tercera",
        "source_type": "nacional",
        "base_url": "https://www.latercera.com",
        "rss_urls": ["https://www.latercera.com/rss.xml"],
        "sitemap_urls": ["https://www.latercera.com/sitemap.xml"],
    },
    {
        "name": "Emol",
        "source_type": "nacional",
        "base_url": "https://www.emol.com",
        "rss_urls": ["https://www.emol.com/rss/rss.asp"],
        "sitemap_urls": ["https://www.emol.com/sitemap.xml"],
    },
    {
        "name": "Cooperativa",
        "source_type": "nacional",
        "base_url": "https://www.cooperativa.cl",
        "rss_urls": ["https://www.cooperativa.cl/noticias/site/tax/port/all/rss_1___1.xml"],
        "sitemap_urls": ["https://www.cooperativa.cl/sitemap.xml"],
    },
    {
        "name": "The Clinic",
        "source_type": "nacional",
        "base_url": "https://www.theclinic.cl",
        "rss_urls": ["https://www.theclinic.cl/feed/"],
        "sitemap_urls": ["https://www.theclinic.cl/sitemap.xml"],
    },
    {
        "name": "ADN Radio Chile",
        "source_type": "nacional",
        "base_url": "https://www.adnradio.cl",
        "rss_urls": ["https://www.adnradio.cl/feed/"],
        "sitemap_urls": ["https://www.adnradio.cl/sitemap.xml"],
    },
    {
        "name": "24 Horas",
        "source_type": "nacional",
        "base_url": "https://www.24horas.cl",
        "rss_urls": [],
        "sitemap_urls": ["https://www.24horas.cl/24horas/site/sitemap_pags.xml"],
    },
    {
        "name": "Meganoticias",
        "source_type": "nacional",
        "base_url": "https://www.meganoticias.cl",
        "rss_urls": [],
        "sitemap_urls": [
            "https://www.meganoticias.cl/sitemaps/sitemap-news.xml",
            "https://www.meganoticias.cl/sitemaps/sitemap-noticias-index-content.xml",
        ],
    },
    {
        "name": "Publimetro Chile",
        "source_type": "nacional",
        "base_url": "https://www.publimetro.cl",
        "rss_urls": [],
        "sitemap_urls": [
            "https://www.publimetro.cl/arc/outboundfeeds/google-news-feed/?outputType=xml",
            "https://www.publimetro.cl/arc/outboundfeeds/sitemap-index/?outputType=xml",
        ],
    },
    {
        "name": "La Cuarta",
        "source_type": "nacional",
        "base_url": "https://www.lacuarta.com",
        "rss_urls": [],
        "sitemap_urls": [
            "https://www.lacuarta.com/arc/outboundfeeds/news-sitemap/?outputType=xml",
            "https://www.lacuarta.com/arc/outboundfeeds/sitemap-index/?outputType=xml",
        ],
    },
    {
        "name": "El Desconcierto",
        "source_type": "nacional",
        "base_url": "https://eldesconcierto.cl",
        "rss_urls": [],
        "sitemap_urls": [
            "https://eldesconcierto.cl/sitemap-news.xml",
            "https://eldesconcierto.cl/sitemap.xml",
        ],
    },
    {
        "name": "Diario Financiero",
        "source_type": "nacional",
        "base_url": "https://www.df.cl",
        "rss_urls": [],
        "sitemap_urls": [
            "https://www.df.cl/noticias/site/sitemap_news.xml",
            "https://www.df.cl/noticias/site/sitemap_pags.xml",
            "https://www.df.cl/noticias/site/list/port/sitemap_df.xml",
        ],
    },
    {
        "name": "BBC Mundo",
        "source_type": "internacional",
        "base_url": "https://www.bbc.com/mundo",
        "rss_urls": ["https://feeds.bbci.co.uk/mundo/rss.xml"],
        "sitemap_urls": ["https://www.bbc.com/sitemaps/https-index-com-news.xml"],
    },
    {
        "name": "El Pais",
        "source_type": "internacional",
        "base_url": "https://elpais.com",
        "rss_urls": ["https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"],
        "sitemap_urls": ["https://elpais.com/sitemap.xml"],
    },
    {
        "name": "DW Espanol",
        "source_type": "internacional",
        "base_url": "https://www.dw.com/es",
        "rss_urls": ["https://rss.dw.com/xml/rss-sp-all"],
        "sitemap_urls": ["https://www.dw.com/sitemap.xml"],
    },
    {
        "name": "France 24 Espanol",
        "source_type": "internacional",
        "base_url": "https://www.france24.com/es",
        "rss_urls": ["https://www.france24.com/es/rss"],
        "sitemap_urls": ["https://www.france24.com/es/sitemap.xml"],
    },
    {
        "name": "CNN Espanol",
        "source_type": "internacional",
        "base_url": "https://cnnespanol.cnn.com",
        "rss_urls": ["https://cnnespanol.cnn.com/feed/"],
        "sitemap_urls": ["https://cnnespanol.cnn.com/sitemap.xml"],
    },
    {
        "name": "Infobae",
        "source_type": "internacional",
        "base_url": "https://www.infobae.com",
        "rss_urls": ["https://www.infobae.com/feeds/rss/"],
        "sitemap_urls": ["https://www.infobae.com/sitemap.xml"],
    },
    {
        "name": "El Mundo",
        "source_type": "internacional",
        "base_url": "https://www.elmundo.es",
        "rss_urls": ["https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml"],
        "sitemap_urls": ["https://www.elmundo.es/sitemap.xml"],
    },
    {
        "name": "Clarin",
        "source_type": "internacional",
        "base_url": "https://www.clarin.com",
        "rss_urls": ["https://www.clarin.com/rss/lo-ultimo/"],
        "sitemap_urls": ["https://www.clarin.com/sitemap.xml"],
    },
]


FAKE_NEWS_SOURCES = [
    {
        "name": "AFP Factual",
        "source_type": "fake_news",
        "base_url": "https://factual.afp.com",
        "rss_urls": ["https://factual.afp.com/rss.xml"],
        "sitemap_urls": ["https://factual.afp.com/sitemap.xml"],
    },
    {
        "name": "Maldita",
        "source_type": "fake_news",
        "base_url": "https://maldita.es",
        "rss_urls": ["https://maldita.es/feed/"],
        "sitemap_urls": ["https://maldita.es/sitemap.xml"],
    },
    {
        "name": "Chequeado",
        "source_type": "fake_news",
        "base_url": "https://chequeado.com",
        "rss_urls": ["https://chequeado.com/feed/"],
        "sitemap_urls": ["https://chequeado.com/sitemap.xml"],
    },
    {
        "name": "Newtral",
        "source_type": "fake_news",
        "base_url": "https://www.newtral.es",
        "rss_urls": ["https://www.newtral.es/feed/"],
        "sitemap_urls": ["https://www.newtral.es/sitemap.xml"],
    },
    {
        "name": "PolitiFact",
        "source_type": "fake_news",
        "base_url": "https://www.politifact.com",
        "rss_urls": ["https://www.politifact.com/rss/factchecks/"],
        "sitemap_urls": ["https://www.politifact.com/sitemap.xml"],
    },
    {
        "name": "Snopes",
        "source_type": "fake_news",
        "base_url": "https://www.snopes.com",
        "rss_urls": ["https://www.snopes.com/feed/"],
        "sitemap_urls": ["https://www.snopes.com/sitemap.xml"],
    },
    {
        "name": "FactCheck.org",
        "source_type": "fake_news",
        "base_url": "https://www.factcheck.org",
        "rss_urls": ["https://www.factcheck.org/feed/"],
        "sitemap_urls": ["https://www.factcheck.org/sitemap.xml"],
    },
]
